name = "day20"
description = "2018 Advent of Code in Ada, Day 20"
version = "0.1.0-dev"

authors = ["John Perry"]
maintainers = ["John Perry <devotus@yahoo.com>"]
maintainers-logins = ["johnperry-math"]
licenses = "GPL-3.0-or-later"
website = ""
tags = ["advent-of-code", "2018", "ada"]
